name: Build and Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install Lua
      run: sudo apt-get install lua5.4 liblua5.4-dev
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.20.0'
    - name: Build
      run: go build -tags lua54 -v ./...
    - name: Test
      run: go test -tags lua54 -v ./...
